<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php

/**
*  General template for displaying group of blocks devided into sections
*/

$group = $block->getGroupName();
$groupCss = $block->getGroupCss();
$groupBehavior = $block->getGroupBehaviour() ? $block->getGroupBehaviour() : '{"tabs":{"openedState":"active"}}';


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cart = $objectManager->get('\Magento\Customer\Model\Session');

if($cart->isLoggedIn()){
?>
<div class="cn_client_info" style="display:none">
    <span class="primary_key"><?=$cart->getCustomer()->getEmail()?></span>
    <span class="_name"><?=$cart->getCustomer()->getName()?></span>
    <span class="_surname"><?=$cart->getCustomer()->getFirstName()?></span>
    <?php if ($cart->getIsSubscribed()): ?>
      <span class="_newsletter_subscription_status">subscribed</span>
    <?php else: ?>
      <span class="_newsletter_subscription_status">unsubscribed</span>
    <?php endif;?>
</div>
<?php } ?>

<?php if ($detailedInfoGroup = $block->getGroupChildNames($group, 'getChildHtml')):?>
    <div class="sections <?= /* @escapeNotVerified */ $groupCss ?>">
        <div class="menu-close-bar">
            <span class="close-btn-wrapper">
                <span class="close-menu">Close</span>
                <span class="close-icon">&times;</span>
            </span>
        </div>
        <?php $layout = $block->getLayout(); ?>
        <div class="section-items <?= /* @escapeNotVerified */ $groupCss ?>-items" data-mage-init='<?= /* @escapeNotVerified */ $groupBehavior ?>'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html) && ($block->getUseForce() != true)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="section-item-title <?= /* @escapeNotVerified */ $groupCss ?>-item-title" data-role="collapsible">
                    <a class="<?= /* @escapeNotVerified */ $groupCss ?>-item-switch" data-toggle="switch" href="#<?= /* @escapeNotVerified */ $alias ?>"><?= /* @escapeNotVerified */ $label ?></a>
                </div>
                <div class="section-item-content <?= /* @escapeNotVerified */ $groupCss ?>-item-content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content"><?= /* @escapeNotVerified */ $html ?></div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>


<script type="text/javascript">
    require(['jquery'],function($){
        $(document).ready(function(){
            jQuery('.close-btn-wrapper').on('click',function(){
                jQuery('html').removeClass('nav-open');
            })
        })
    })
</script>
