<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
/* Get base url with index When index.php enable at Url */
$baseUrl = $storeManager->getStore()->getBaseUrl();
/* Result  http://www.example.com/ or http://www.example.com/index.php  depends SEo rewite settng*/
/* it always give the URL without Index.php either index.php enable for Url */
$baseUrlWithOutIndexPhp = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
// $baseUrl  result = http://example.com/

/* It is give url with index.php whenever  seo rewrite not enable mean when  Index.php show at Url  */

$linkUrl= $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

 /* $linkUrl  result = http://example.com/index.php/
 whenever  seo rewrite not enable mean when  Index.php show at Url

 but when  SEO Rewrite enabled

 Then it show result = http://example.com/

 */

$statiContenteUrl =$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_STATIC);
/* Result $statiContenteUrl = http://example.com/pub/static/version1507042743/
 In this part  version1507042743 is 1507042743 static content version which dynamcically created
*/

$mediaUrl =  $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
/* Result $mediaUrl = http://example.com/pub/media/

*/

$getLocale = $objectManager->get('Magento\Framework\Locale\Resolver');
$haystack  = $getLocale->getLocale();
$lang = strstr($haystack, '_', true);


$div_newsletter='';
if(isset($_SESSION['customer']['my_value'])){
  $div_newsletter = '<div class="cn_newsletter_subscribe" style="display:none"><span class="email">'.$_SESSION['customer']['my_value'].'</span></div>';
  unset($_SESSION['customer']['my_value']);
}
?>
<div class="container">
  <?php
    if($div_newsletter != ''){
      print_r($div_newsletter);
    }
  ?>
	<div class="block newsletter">
		<div class="content">
			<div class="discount-msg">
				<h3 class="msg"><?= $block->escapeHtml(__('We have a 10% discount for you! Subscribe and keep informed of all our offers.')) ?></h3>	
			</div>
			<div class="subscribe-section">
				<form class="form subscribe"
					novalidate
					action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
					method="post"
					data-mage-init='{"validation": {"errorClass": "mage-error"}}'
					id="newsletter-validate-detail">
					<div class="field newsletter">
						<label class="label" for="newsletter"><span><?= $block->escapeHtml(__('SIGN UP FOR OUR E-NEWS')) ?></span></label>
						<div class="control">
							<input name="email" type="email" id="newsletter"
										placeholder="<?= $block->escapeHtmlAttr(__('Email')) ?>"
										data-validate="{required:true, 'validate-email':true}"/>
						</div>
						<div class="actions">
							<button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
								<span><?= $block->escapeHtml(__('Send')) ?></span>
							</button>
						</div>
					</div>

					<div class="field privacy required">
						<div class="control">
						<?php $link = $baseUrlWithOutIndexPhp.'./privacy/'; ?>
							<div class="checkbox-container">
							<input type="checkbox" name="privacy" value="1" class="checkbox" data-validate="{required:true}" />
							<div class="checkmark"></div>
							</div>
							<div class="customer-acceptance">
								<?php echo __('I have read and accept the <a href="./privacy/">Privacy policy</a>',$link); ?>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
