<?php
$product = $this->getProductData();
$escaper = $this->getHtmlEscaper();
?>
<!-- Connectif Product Tags -->

<div class="cn_product_visited" style="display:none">
    <span class="url"><?php echo $escaper->escapeHtml($product['url']); ?></span>
    <span class="product_id"><?php echo $escaper->escapeHtml($product['product_id']); ?></span>
    <span class="name"><?php echo $escaper->escapeHtml($product['name']); ?></span>
    <span class="description"><?php echo $escaper->escapeHtml($product['description']); ?></span>
    <span class="image_url"><?php echo $escaper->escapeHtml($product['image_url']); ?></span>
    <span class="unit_price"><?php echo $escaper->escapeHtml($product['unit_price']); ?></span>
    <span class="availability"><?php echo $escaper->escapeHtml($product['availability']); ?></span>


    <?php if (array_key_exists("unit_price_original", $product) && is_numeric($product['unit_price_original'])) {?>
        <span class="unit_price_original"><?php echo $escaper->escapeHtml($product['unit_price_original']); ?></span>
    <?php }?>

    <?php if (array_key_exists("unit_price_without_vat", $product) && is_numeric($product['unit_price_without_vat'])) {?>
        <span class="unit_price_without_vat"><?php echo $escaper->escapeHtml($product['unit_price_without_vat']); ?></span>
    <?php }?>

    <?php if (array_key_exists("discounted_percentage", $product) && is_numeric($product['discounted_percentage'])) {?>
        <span class="discounted_percentage"><?php echo $escaper->escapeHtml($product['discounted_percentage']); ?></span>
    <?php }?>

    <?php if (array_key_exists("discounted_amount", $product) && is_numeric($product['discounted_amount'])) {?>
        <span class="discounted_amount"><?php echo $escaper->escapeHtml($product['discounted_amount']); ?></span>
    <?php }?>

    <?php if (array_key_exists("brand", $product) && $product['brand'] != false) {?>
        <span class="brand"><?php echo $escaper->escapeHtml($product['brand']); ?></span>
    <?php }?>

    <?php if (array_key_exists("rating_count", $product) && is_numeric($product['rating_count'])) {?>
        <span class="rating_count"><?php echo $escaper->escapeHtml($product['rating_count']); ?></span>
    <?php }?>

    <?php if (array_key_exists("rating_value", $product) && is_numeric($product['rating_value'])) {?>
        <span class="rating_value"><?php echo $escaper->escapeHtml($product['rating_value']); ?></span>
    <?php }?>

    <?php if (array_key_exists("review_count", $product) && is_numeric($product['review_count'])) {?>
        <span class="review_count"><?php echo $escaper->escapeHtml($product['review_count']); ?></span>
    <?php }?>

    <?php if (array_key_exists("thumbnail_url", $product)) {?>
        <span class="thumbnail_url"><?php echo $escaper->escapeHtml($product['thumbnail_url']); ?></span>
    <?php }?>

    <?php foreach ($product['relatedProductIds'] as $key => $relatedProductId): ?>
        <span class="related_external_product_id"><?php echo $escaper->escapeHtml($relatedProductId); ?></span>
    <?php endforeach;?>

    <?php foreach ($product['categories'] as $key => $value): ?>
        <span class="category"><?php echo $escaper->escapeHtml($value); ?></span>
    <?php endforeach;?>
</div>